export const taskType = {
  ADD_TASK: "ADD_TASK",
  GET_TASK_LIST: "GET_TASK_LIST",
  API_CALL_START: "API_CALL_START",
  API_CALL_SUCCESS: "API_CALL_SUCCESS",
  API_CALL_FAIL: "API_CALL_FAIL",
  REMOVE_TASK_FROM_LIST: "REMOVE_TASK_FROM_LIST",
  UPDATE_TASK_IN_LIST: "UPDATE_TASK_IN_LIST",
  ADD_NEW_TASK_TO_LIST: "ADD_NEW_TASK_TO_LIST"
};
